# Generated by Django 4.2.6 on 2023-10-08 20:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('duration', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='links',
            field=models.ManyToManyField(blank=True, related_name='links_to', to='api.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/None/'),
        ),
    ]
