# Generated by Django 4.2.6 on 2023-10-14 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.image'),
        ),
    ]
