# Generated by Django 4.2.6 on 2023-10-08 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_links_image_links_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='expiring_link',
        ),
        migrations.RemoveField(
            model_name='image',
            name='expiring_link_created_at',
        ),
        migrations.RemoveField(
            model_name='image',
            name='expiring_link_duration',
        ),
    ]
