# Generated by Django 4.2.6 on 2023-10-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_image_expiring_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/<django.db.models.query_utils.DeferredAttribute object at 0x000001BF11385510>/'),
        ),
    ]
