# Generated by Django 4.2.6 on 2023-10-08 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_image_username_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='username',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to="images/b'PGRqYW5nby5kYi5tb2RlbHMuZmllbGRzLnJlbGF0ZWQuRm9yZWlnbktleT4='"),
        ),
    ]
