# Generated by Django 4.2.6 on 2023-10-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='links',
            name='image',
            field=models.ImageField(default='xxx', upload_to='images/2023/10/09'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='links',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='links',
            field=models.ManyToManyField(blank=True, to='api.image'),
        ),
    ]
