# Generated by Django 4.2.6 on 2023-10-09 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_image_image_links_image_links_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='original_image',
            field=models.ImageField(default='', upload_to='images/2023/10/09'),
            preserve_default=False,
        ),
    ]
