# Generated by Django 4.2.6 on 2023-10-12 00:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_image_original_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='original_image',
            field=models.ImageField(upload_to=api.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='links',
            name='image',
            field=models.ImageField(upload_to='images/2023/10/12'),
        ),
    ]
