# Generated by Django 4.2.6 on 2023-10-12 01:41

import api.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_image_original_image_alter_links_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=api.models.get_upload_path)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('link', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('duration', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Links',
        ),
        migrations.AlterField(
            model_name='image',
            name='links',
            field=models.ManyToManyField(blank=True, to='api.link'),
        ),
    ]
