# Generated by Django 4.2.6 on 2023-10-13 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_link_delete_links_alter_image_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='original_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='links',
        ),
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
