# Generated by Django 4.2.6 on 2023-10-13 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_original_image_image_image_remove_image_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
    ]
