# Generated by Django 4.2.6 on 2023-10-14 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_remove_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='link',
            name='img',
        ),
        migrations.RemoveField(
            model_name='link',
            name='size',
        ),
        migrations.AddField(
            model_name='link',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='image',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='api.image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='link',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.URLField(),
        ),
    ]
