# Generated by Django 4.2.6 on 2023-10-12 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thumbnail_sizes',
            new_name='Thumbnail_size',
        ),
    ]
